// <auto-generated />
using System;
using FixItNow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FixItNow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908160611_AddUserAuth")]
    partial class AddUserAuth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FixItNow.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Fix and balance ceiling fans",
                            Name = "Ceiling Fan Repair",
                            Price = 300m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Wall mount LED/LCD/Smart TVs",
                            Name = "TV Mounting",
                            Price = 500m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 20,
                            Description = "Install or replace light fixtures",
                            Name = "Light Installation",
                            Price = 450m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Install new ceiling fans",
                            Name = "Ceiling Fan Installation",
                            Price = 650m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 14,
                            Description = "Install smart switches and dimmers",
                            Name = "Smart Switch/Dimmer Setup",
                            Price = 550m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Fix leaking pipes and joints",
                            Name = "Pipe Leak Repair",
                            Price = 400m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 12,
                            Description = "Seal bathtubs, sinks, windows",
                            Name = "Sealing & Caulking",
                            Price = 350m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Mount and connect water filters",
                            Name = "Install Water Filter",
                            Price = 700m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Local house shifting services",
                            Name = "House Shifting (Local)",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 25,
                            Description = "Assist with packing, loading, unloading",
                            Name = "Help Moving",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            Description = "Move heavy furniture and appliances",
                            Name = "Heavy Lifting",
                            Price = 800m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Move furniture within or between homes",
                            Name = "Furniture Movers",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 26,
                            Description = "Pickup and dispose unwanted items",
                            Name = "Junk Pickup",
                            Price = 900m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Assemble outdoor sets",
                            Name = "Patio Furniture Assembly",
                            Price = 600m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Assemble office and gaming desks",
                            Name = "Desk Assembly",
                            Price = 450m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "Assemble dressers and chests",
                            Name = "Dresser Assembly",
                            Price = 500m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Assemble beds and frames",
                            Name = "Bed Assembly",
                            Price = 550m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Assemble bookshelves and storage units",
                            Name = "Bookshelf Assembly",
                            Price = 400m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "Assemble wardrobes/closets",
                            Name = "Wardrobe Assembly",
                            Price = 700m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 16,
                            Description = "Install shelves and closet rods",
                            Name = "Install Shelves, Rods & Hooks",
                            Price = 350m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 13,
                            Description = "Mount blinds and curtains",
                            Name = "Install Blinds & Window Treatments",
                            Price = 500m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            Description = "Mount frames, mirrors, and decor",
                            Name = "Hang Art, Mirror & Decor",
                            Price = 300m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            Description = "Mounting for various items",
                            Name = "General Mounting",
                            Price = 300m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Patch and smooth drywall",
                            Name = "Drywall Repair",
                            Price = 650m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 13,
                            Description = "Repair window hardware & blinds",
                            Name = "Window & Blinds Repair",
                            Price = 450m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Description = "Fix hinges, handles, drawers",
                            Name = "Door, Cabinet, & Furniture Repair",
                            Price = 550m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Description = "Install or fix appliances",
                            Name = "Appliance Installation & Repairs",
                            Price = 900m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            Description = "Standard home cleaning",
                            Name = "House Cleaning",
                            Price = 800m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Description = "Intensive deep clean",
                            Name = "Deep Cleaning",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            Description = "Cleaning for moving",
                            Name = "Move In/Out Cleaning",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            Description = "Shampoo and clean carpets",
                            Name = "Carpet Cleaning",
                            Price = 900m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 19,
                            Description = "Planting, weeding, pruning",
                            Name = "Gardening Services",
                            Price = 700m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 19,
                            Description = "Mow and edge lawns",
                            Name = "Lawn Care & Mowing",
                            Price = 600m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 19,
                            Description = "Clear and flush gutters",
                            Name = "Gutter Cleaning",
                            Price = 550m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 23,
                            Description = "Install or fix fences",
                            Name = "Fence Installation & Repair",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 27,
                            Description = "Declutter and organize closets",
                            Name = "Closet Organization",
                            Price = 700m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            Description = "Errands, scheduling, admin tasks",
                            Name = "Personal Assistant",
                            Price = 500m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 28,
                            Description = "Queue on your behalf",
                            Name = "Wait in Line",
                            Price = 250m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 28,
                            Description = "Shop and deliver groceries",
                            Name = "Grocery Shopping & Delivery",
                            Price = 300m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 15,
                            Description = "Paint rooms and interiors",
                            Name = "Interior Painting",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 11,
                            Description = "Install or repair tiles/flooring",
                            Name = "Flooring & Tiling Help",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 14,
                            Description = "Set up smart devices/hubs",
                            Name = "Smart Home Installation",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 33,
                            Description = "Install and remove lights",
                            Name = "Hang Christmas Lights",
                            Price = 700m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 34,
                            Description = "Clear snow from paths and drives",
                            Name = "Snow Removal",
                            Price = 900m
                        });
                });

            modelBuilder.Entity("FixItNow.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plumbing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home Moving"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Carpentry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Furniture Assembly"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Home Repairs"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Heavy Lifting"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Home Cleaning"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Personal Assistant"
                        },
                        new
                        {
                            Id = 10,
                            Name = "General Mounting"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Flooring & Tiling"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sealing & Caulking"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Windows & Blinds"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Smart Home"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Shelves & Hooks"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Baby Proofing"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Yardwork & Landscaping"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Light Installation"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cabinets"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Wallpapering"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Fence & Deck"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Doorbell & Home Theater"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Packing & Moving Help"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Junk Removal"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Organization"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Delivery & Errands"
                        },
                        new
                        {
                            Id = 29,
                            Name = "IKEA Services"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Virtual & Online"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Office Services"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Contactless Tasks"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Holidays & Seasonal"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Winter Tasks"
                        });
                });

            modelBuilder.Entity("FixItNow.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("FixItNow.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            PasswordHash = "0000",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FixItNow.Models.Service", b =>
                {
                    b.HasOne("FixItNow.Models.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FixItNow.Models.ServiceRequest", b =>
                {
                    b.HasOne("FixItNow.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
